# Generated by Django 5.1 on 2024-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_seat_is_reserved_seat_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='num_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
